### ISSUE TITLE
2d predictions

### ISSUE THREAD

**Issue by bearpaw** [geopavlakos/harvesting#2]
Thanks for the code. Would you also please release the predictions generated by hourglass? Thank you very much!

**Comment by mkocabas** [comment]
You can take a look at [here](https://github.com/una-dinosauria/3d-pose-baseline#first-of-all) if you don't hear from Pavlakos. Hope it helps!

**Comment by bearpaw** [comment]
Thank you @mkocabas ! It helps. And I also managed to run the torch code by using docker :)

And congrats for your new CVPR paper!

**Comment by mkocabas** [comment]
> Thank you @mkocabas ! It helps. And I also managed to run the torch code by using docker :)

Great!

> And congrats for your new CVPR paper!

Thanks! Will you attend the conference?

**Comment by bearpaw** [comment]
I may not able to attend the conference this year. Hope you enjoy it :)
